apiVersion: v1
kind: Pod
metadata:
  name: htaroowai-demo
  labels:
    app: htaroowai-demo
spec:
  containers:
  - image: "htaroowaidemo.azurecr.io/htaroowai-demo:latest"
    name: htaroowaidemo-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: htaroowai-demo
spec:
  selector:
    app: htaroowai-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: htaroowai-demo
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: htaroowai-demo
            port:
              number: 80
        pathType: Exact
